[package]
name = "colink-protocol-remote-storage"
version = "0.1.3"
edition = "2021"

[dependencies]
colink = "0.3.0"
prost = "0.10"
tokio = "1.24"
tracing = "0.1"

[build-dependencies]
prost-build = "0.10"
