[package]
name = "remote_storage"
version = "0.1.3"
keywords = ["remote storage"]
description = "remote storage"
entrypoint = "cargo run"

[remote_storage]
name = "remote_storage"
description = "remote storage"
